environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\venv"

  matrix:
    - TOXENV: py27-defaultreactor
      PYTHON: "C:\\Python27"

    - TOXENV: py27-defaultreactor
      PYTHON: "C:\\Python27-x64"

    - TOXENV: py35-defaultreactor, py35-pyqt5reactor, py35-pyside2reactor, py35-asyncioreactor
      PYTHON: "C:\\Python35"

    - TOXENV: py35-defaultreactor, py35-pyqt5reactor, py35-pyside2reactor, py35-asyncioreactor
      PYTHON: "C:\\Python35-x64"

    - TOXENV: py36-defaultreactor, py36-pyqt5reactor, py36-pyside2reactor, py36-asyncioreactor
      PYTHON: "C:\\Python36"

    - TOXENV: py36-defaultreactor, py36-pyqt5reactor, py36-pyside2reactor, py36-asyncioreactor
      PYTHON: "C:\\Python36-x64"

    - TOXENV: py37-defaultreactor, py37-pyqt5reactor, py37-pyside2reactor, py37-asyncioreactor
      PYTHON: "C:\\Python37"

    - TOXENV: py37-defaultreactor, py37-pyqt5reactor, py37-pyside2reactor, py37-asyncioreactor
      PYTHON: "C:\\Python37-x64"

    - TOXENV: py38-defaultreactor, py38-pyqt5reactor, py38-pyside2reactor, py38-asyncioreactor
      PYTHON: "C:\\Python38"

    - TOXENV: py38-defaultreactor, py38-pyqt5reactor, py38-pyside2reactor, py38-asyncioreactor
      PYTHON: "C:\\Python38-x64"

install:
  # https://github.com/pypa/virtualenv/issues/1050
  - pip install -U git+https://github.com/pypa/virtualenv@e8163e83a92c9098f51d390289323232ece15e3b
  - virtualenv -p "%PYTHON%\\python.exe" "%VENV%"
  - "%VENV%\\Scripts\\activate"
  - pip install tox

build: off

test_script:
  - tox
